#!/usr/bin/env python
# encoding: utf-8

import requests
from BeautifulSoup import BeautifulSoup

#config.action_controller.allow_forgery_protection = false
#in environment.rb /var/www/gitorious/config

class GitoriousClient(object):

    def __init__(self, **args):
        self.hosturi = args['hosturi']
        self.auth=(args['user'],args['pwd'])
        self.session = requests.session(auth=self.auth)

    def get_authtoken(self):
        r = session.get('%s/new' % self.hosturi, verify=False)
        soup = BeautifulSoup(r.content)
        inputauth = soup.find('input', attrs={'name':'authenticity_token'})
        authenticity_token=dict(inputauth.attrs)['value']
        return authenticity_token

    def create_project(self, projectname):
        data = {
                #'authenticity_token': authenticity_token,
                'project[title]': projectname,
                'project[slug]': projectname,
                'project[owner_type]': 'User',
                'project[owner_id]': '',
                'project[tag_list]': '',
                'project[license]':'Academic Free License v3.0',
                'project[home_url]':'',
                'project[mailinglist_url]':'',
                'project[bugtracker_url]':'',
                'project[wiki_enabled]':1,
                'project[description]': 'no description yet',
                'commit':'Create project'}

        r = self.session.post('%s/projects' % self.hosturi, verify=False, data=data)
        if not r.ok:
            raise Exception('counld no create project %s' % projectname)

    def create_repo(self, projectname, repositoryname):
        data = {'repository[name]': repositoryname,
                'repository[description]' : '',
                'repository[merge_requests_enabled]': 1,
                'commit': 'Create repository'}

        r = self.session.post('%s/%s/repositories' % (self.hosturi, projectname), verify=False, data=data)
        if r.ok:
            print 'project %s @ repo %s created successfully' % (projectname , repositoryname)
        else:
            print 'counld no create project %s @ repo %s' % (projectname, repositoryname)


    def delete_project(self, projectname):

        data = {"_method": "delete",
                "commit": "YES I am sure I want to delete this project permanently"}
        r = self.session.post('%s/%s' %(self.hosturi, projectname), verify=False, data=data)
        if r.ok:
            print 'deleted project %s' % projectname
        else:
            print 'Could not delete project %s'  % projectname

    def delete_repo(self, projectname, repositoryname):
        data = {"_method": "delete",
                "commit": "YES I am sure I want to delete this repository permanently"}
        r = self.session.post('%s/%s/%s' %(self.hosturi, projectname, repositoryname), verify=False, data=data)
        if r.ok:
            print 'deleted project %s @ repo %s' % (projectname, repositoryname)
        else:
            print 'Could not delete project %s @ repo %s'  % (projectname, repositoryname)



def run(options):

    projectname = options['projectname']
    g = GitoriousClient(**options)

    if options["delete"] and "repositoryname" in options:
        g.delete_repo(projectname, options["repositoryname"])
    elif options["delete"]:
        g.delete_project(projectname)
    else:
        repositoryname = options.get('repositoryname', 'projectname')
        g.create_project(projectname)
        g.create_repo(projectname, repositoryname)


def main():
    from optparse import OptionParser

    usage = 'usage: %prog [options] user -h for help'
    parser = OptionParser(usage)
    parser.add_option('-f', '--host', action='store',
    type='string', dest='hosturi', help='gitorious host')
    parser.add_option('-u', '--user', action='store',
    type='string', dest='user', help='user name')
    parser.add_option('-p', '--pwd', action='store',
    type='string', dest='pwd', help='password')
    parser.add_option('-i', '--project', action='store',
    type='string', dest='projectname', help='projectname')
    parser.add_option('-r', '--repo', action='store',
    type='string', dest='repositoryname', help='projectname')
    parser.add_option('-d', '--delete', action='store_true',
    dest='delete', help='delete project', default=False)

    (options, args) = parser.parse_args()
    #remove None value's
    voptions = vars(options)
    voptions = dict([(k, v) for k, v in voptions.iteritems() if v is not None])

    if set(['hosturi', 'user', 'pwd', 'projectname']) - set(voptions.keys()):
        parser.print_help()
    else:
        run(voptions)

if __name__ == '__main__':
    main()
